name: 'Build AIRADCR'

on:
  workflow_dispatch:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'
  release:
    types: [ published ]

jobs:
  build:
    permissions:
      contents: write
    timeout-minutes: 60
    strategy:
      fail-fast: false
      matrix:
        settings:
          - platform: 'macos-latest'
            args: '--target aarch64-apple-darwin'
          - platform: 'macos-latest'
            args: '--target x86_64-apple-darwin'
          - platform: 'ubuntu-22.04'
            args: ''
          - platform: 'windows-latest'
            args: ''

    runs-on: ${{ matrix.settings.platform }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies (ubuntu only)
        if: matrix.settings.platform == 'ubuntu-22.04'
        run: |
          sudo apt-get update
          sudo apt-get install -y libwebkit2gtk-4.0-dev libgtk-3-dev libayatana-appindicator3-dev librsvg2-dev patchelf

      - name: Rust setup
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.settings.platform == 'macos-latest' && 'aarch64-apple-darwin,x86_64-apple-darwin' || '' }}

      - name: Rust cache
        uses: swatinem/rust-cache@v2
        with:
          workspaces: './src-tauri -> target'

      - name: Sync node version and setup cache
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'

      - name: Install frontend dependencies
        run: npm ci

      - name: Build all required icons (robust)
        run: node scripts/build-icons-robust.cjs

      - name: Validate all icons and assets  
        run: node scripts/validate-icons.cjs

      - name: Build the app
        run: npx tauri build ${{ matrix.settings.args }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Pre-check files before signing (Windows)
        if: matrix.settings.platform == 'windows-latest'
        shell: powershell
        run: |
          Write-Host "📋 PRÉ-CHECK DES FICHIERS À SIGNER"
          Write-Host "=================================="
          
          Write-Host "`n🔍 Recherche airadcr-desktop.exe:"
          if (Test-Path "src-tauri\target\release\airadcr-desktop.exe") {
            $exe = Get-Item "src-tauri\target\release\airadcr-desktop.exe"
            Write-Host "  ✅ Trouvé: $($exe.FullName)"
            Write-Host "  📦 Taille: $([math]::Round($exe.Length / 1MB, 2)) MB"
          } else {
            Write-Host "  ❌ INTROUVABLE"
          }
          
          Write-Host "`n🔍 Recherche fichiers MSI:"
          $msiFiles = Get-ChildItem -Path "src-tauri\target\release\bundle\msi\*.msi" -ErrorAction SilentlyContinue
          if ($msiFiles) {
            Write-Host "  ✅ Trouvé $($msiFiles.Count) fichier(s):"
            foreach ($msi in $msiFiles) {
              Write-Host "    - $($msi.Name) ($([math]::Round($msi.Length / 1MB, 2)) MB)"
            }
          } else {
            Write-Host "  ❌ AUCUN MSI TROUVÉ"
          }
          
          Write-Host "`n🔍 Recherche fichiers NSIS:"
          $nsisFiles = Get-ChildItem -Path "src-tauri\target\release\bundle\nsis\*.exe" -ErrorAction SilentlyContinue
          if ($nsisFiles) {
            Write-Host "  ✅ Trouvé $($nsisFiles.Count) fichier(s):"
            foreach ($nsis in $nsisFiles) {
              Write-Host "    - $($nsis.Name) ($([math]::Round($nsis.Length / 1MB, 2)) MB)"
            }
          } else {
            Write-Host "  ❌ AUCUN NSIS TROUVÉ"
          }
          
          Write-Host "`n=================================="

      - name: Sign main executable (Windows)
        if: matrix.settings.platform == 'windows-latest'
        timeout-minutes: 12
        uses: sslcom/esigner-codesign@develop
        with:
          command: sign
          username: ${{ secrets.ESIGNER_USERNAME }}
          password: ${{ secrets.ESIGNER_PASSWORD }}
          credential_id: ${{ secrets.CREDENTIAL_ID }}
          totp_secret: ${{ secrets.ESIGNER_TOTP_SECRET }}
          file_path: ${{ github.workspace }}/src-tauri/target/release/airadcr-desktop.exe
          output_path: ${{ github.workspace }}/artifacts
          override: true

      - name: Collect signing logs on failure (EXE)
        if: failure() && matrix.settings.platform == 'windows-latest'
        shell: powershell
        run: |
          Write-Host "🔍 Recherche des logs CodeSignTool..."
          $logPath = "codesign\CodeSignTool-v1.3.0\logs"
          if (Test-Path $logPath) {
            Get-ChildItem -Path $logPath -Recurse | ForEach-Object {
              Write-Host "`n📄 Contenu de $($_.Name):"
              Get-Content $_.FullName -Tail 200
            }
          } else {
            Write-Host "⚠️ Aucun log trouvé dans $logPath"
          }

      - name: Sign MSI installers (Windows)
        if: matrix.settings.platform == 'windows-latest'
        timeout-minutes: 12
        uses: sslcom/esigner-codesign@develop
        with:
          command: sign
          username: ${{ secrets.ESIGNER_USERNAME }}
          password: ${{ secrets.ESIGNER_PASSWORD }}
          credential_id: ${{ secrets.CREDENTIAL_ID }}
          totp_secret: ${{ secrets.ESIGNER_TOTP_SECRET }}
          file_path: ${{ github.workspace }}/src-tauri/target/release/bundle/msi/*.msi
          output_path: ${{ github.workspace }}/artifacts
          override: true

      - name: Collect signing logs on failure (MSI)
        if: failure() && matrix.settings.platform == 'windows-latest'
        shell: powershell
        run: |
          Write-Host "🔍 Recherche des logs CodeSignTool..."
          $logPath = "codesign\CodeSignTool-v1.3.0\logs"
          if (Test-Path $logPath) {
            Get-ChildItem -Path $logPath -Recurse | ForEach-Object {
              Write-Host "`n📄 Contenu de $($_.Name):"
              Get-Content $_.FullName -Tail 200
            }
          } else {
            Write-Host "⚠️ Aucun log trouvé dans $logPath"
          }

      - name: Sign NSIS installers (Windows)
        if: matrix.settings.platform == 'windows-latest'
        timeout-minutes: 12
        uses: sslcom/esigner-codesign@develop
        with:
          command: sign
          username: ${{ secrets.ESIGNER_USERNAME }}
          password: ${{ secrets.ESIGNER_PASSWORD }}
          credential_id: ${{ secrets.CREDENTIAL_ID }}
          totp_secret: ${{ secrets.ESIGNER_TOTP_SECRET }}
          file_path: ${{ github.workspace }}/src-tauri/target/release/bundle/nsis/*.exe
          output_path: ${{ github.workspace }}/artifacts
          override: true

      - name: Collect signing logs on failure (NSIS)
        if: failure() && matrix.settings.platform == 'windows-latest'
        shell: powershell
        run: |
          Write-Host "🔍 Recherche des logs CodeSignTool..."
          $logPath = "codesign\CodeSignTool-v1.3.0\logs"
          if (Test-Path $logPath) {
            Get-ChildItem -Path $logPath -Recurse | ForEach-Object {
              Write-Host "`n📄 Contenu de $($_.Name):"
              Get-Content $_.FullName -Tail 200
            }
          } else {
            Write-Host "⚠️ Aucun log trouvé dans $logPath"
          }

      - name: Verify code signatures (Windows)
        if: matrix.settings.platform == 'windows-latest'
        shell: powershell
        run: |
          Write-Host "📋 VÉRIFICATION DES SIGNATURES"
          Write-Host "================================"
          
          $files = Get-ChildItem -Path "src-tauri\target\release\" -Include "*.exe","*.msi" -Recurse
          
          $validCount = 0
          $invalidCount = 0
          
          foreach ($file in $files) {
            $sig = Get-AuthenticodeSignature $file.FullName
            
            if ($sig.Status -eq 'Valid') {
              Write-Host "✅ $($file.Name): Signature valide"
              Write-Host "   Signataire: $($sig.SignerCertificate.Subject)"
              $validCount++
            } else {
              Write-Host "❌ $($file.Name): Status $($sig.Status)"
              $invalidCount++
            }
          }
          
          Write-Host ""
          Write-Host "================================"
          Write-Host "📊 Résumé:"
          Write-Host "  ✅ Signatures valides: $validCount"
          Write-Host "  ❌ Signatures invalides: $invalidCount"
          Write-Host "================================"
          
          if ($invalidCount -gt 0) {
            Write-Error "❌ Certains fichiers ne sont pas correctement signés"
            exit 1
          }

      - name: Debug bundle contents (Windows)
        if: matrix.settings.platform == 'windows-latest'
        run: |
          echo "Listing Windows bundle directory contents:"
          if (Test-Path "src-tauri/target/release/bundle/") { Get-ChildItem -Path "src-tauri/target/release/bundle/" -Recurse } else { echo "Bundle directory not found" }
          Get-ChildItem -Path "src-tauri/target/" -Include "*.exe","*.msi" -Recurse -ErrorAction SilentlyContinue
        shell: powershell

      - name: Debug bundle contents (Unix)
        if: matrix.settings.platform != 'windows-latest'
        run: |
          echo "Listing bundle directory contents:"
          ls -la src-tauri/target/release/bundle/ || echo "Bundle directory not found"
          find src-tauri/target/ -name "*.exe" -o -name "*.msi" -o -name "*.dmg" -o -name "*.deb" -o -name "*.AppImage" || echo "No build artifacts found"

      - name: Upload Windows artifacts
        uses: actions/upload-artifact@v4
        if: matrix.settings.platform == 'windows-latest'
        with:
          name: build-windows-latest
          path: |
            src-tauri/target/release/bundle/msi/*.msi
            src-tauri/target/release/bundle/nsis/*.exe
            src-tauri/target/release/*.exe
          retention-days: 30

      - name: Upload macOS artifacts
        uses: actions/upload-artifact@v4
        if: matrix.settings.platform == 'macos-latest'
        with:
          name: build-macos-${{ contains(matrix.settings.args, 'aarch64') && 'arm64' || 'intel' }}
          path: |
            src-tauri/target/*/release/bundle/dmg/*.dmg
            src-tauri/target/*/release/bundle/macos/*.app
          retention-days: 30

      - name: Upload Linux artifacts
        uses: actions/upload-artifact@v4
        if: matrix.settings.platform == 'ubuntu-22.04'
        with:
          name: build-ubuntu-22.04
          path: |
            src-tauri/target/release/bundle/deb/*.deb
            src-tauri/target/release/bundle/appimage/*.AppImage
          retention-days: 30